version: '3'

networks:
  laravel:

services:

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - laravel

  php:
    build:
      context: ./php
    volumes:
      - ..:/var/www
    ports:
      - '9000:9000'
    networks:
      - laravel

  nginx:
    image: nginx:1.19-alpine
    ports:
      - '80:80'
    volumes:
      - ..:/var/www
      - .\nginx\conf.d\laravel.conf:/etc/nginx/conf.d/laravel.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
